=== ASLavanya/18IT045_xml_book_cataloging/xml 2/fiction.dtd
<?xml version="1.0" en=coding = "UTF-8"?>
<!ELEMENT fiction(book+)>
<!ELEMENT book(title,author+,description,setting,pages,published,publisher,avg_rating)>
<!ELEMENT title(#PCDATA)>
<!ELEMENT author(#PCDATA)>
<!ELEMENT description(#PCDATA)>
<!ELEMENT setting(#PCDATA)>
<!ELEMENT pages(#PCDATA)>
<!ELEMENT published(#PCDATA)>
<!ELEMENT publisher(#PCDATA)>
<!ELEMENT avg_rating(#PCDATA)>

=== ASLavanya/18IT045_xml_book_cataloging/xml 2/fictional.xml
<?xml version="1.0" encoding = "UTF-8"?>
<!--<!DOCTYPE fiction SYSTEM "fiction.dtd">-->
<?xml-stylesheet type="text/xsl" href="style.xsl" ?>

<fiction>

<book>
<title>To Kill a Mockingbird</title>
<author>Harper Lee</author>
<description>The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it, To Kill A Mockingbird became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic. 
Compassionate, dramatic, and deeply moving, To Kill A Mockingbird takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.</description>
<setting>Maycomb, Alabama, 1933 (United States)</setting>
<pages>324</pages>
<published>May 23rd 2006</published>
<publisher>Harper Perennial Modern Classics</publisher>
<avg_rating>4.28</avg_rating>
</book>

<book>
<title>1984</title>
<author>George Orwell</author>
<description>Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its futuristic purgatory becomes more real. Published in 1949, the book offers political satirist George Orwell's nightmarish vision of a totalitarian, bureaucratic world and one poor stiff's attempt to find individuality. The brilliance of the novel is Orwell's prescience of modern life—the ubiquity of television, the distortion of the language—and his ability to construct such a thorough version of hell. Required reading for students since it was published, it ranks among the most terrifying novels ever written.</description>
<setting>London, England, 1984 (United Kingdom)</setting>
<pages>237</pages>
<published>September 3rd 2013</published>
<publisher>Houghton Mifflin Harcourt</publisher>
<avg_rating>4.19</avg_rating>
</book>

<book>
<title>The Great Gatsby</title>
<author> Francis Scott Fitzgerald</author>
<description>The Great Gatsby, F. Scott Fitzgerald's third book, stands as the supreme achievement of his career. This exemplary novel of the Jazz Age has been acclaimed by generations of readers. The story is of the fabulously wealthy Jay Gatsby and his new love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted "gin was the national drink and sex the national obsession," it is an exquisitely crafted tale of America in the 1920s.
The Great Gatsby is one of the great classics of twentieth-century literature.</description>
<setting>Long Island, New York, 1925 (United States)</setting>
<pages>200</pages>
<published> April 10th 1925</published>
<publisher>Scribner</publisher>
<avg_rating>3.92</avg_rating>
</book>

<book>
<title>Harry Potter and the Sorcerer's Stone</title>
<author> J.K. Rowling</author>
<description>Harry Potter's life is miserable. His parents are dead and he's stuck with his heartless relatives, who force him to live in a tiny closet under the stairs. But his fortune changes when he receives a letter that tells him the truth about himself: he's a wizard. A mysterious visitor rescues him from his relatives and takes him to his new home, Hogwarts School of Witchcraft and Wizardry.

After a lifetime of bottling up his magical powers, Harry finally feels like a normal kid. But even within the Wizarding community, he is special. He is the boy who lived: the only person to have ever survived a killing curse inflicted by the evil Lord Voldemort, who launched a brutal takeover of the Wizarding world, only to vanish after failing to kill Harry.

Though Harry's first year at Hogwarts is the best of his life, not everything is perfect. There is a dangerous secret object hidden within the castle walls, and Harry believes it's his responsibility to prevent it from falling into evil hands. But doing so will bring him into contact with forces more terrifying than he ever could have imagined.

Full of sympathetic characters, wildly imaginative situations, and countless exciting details, the first installment in the series assembles an unforgettable magical world and sets the stage for many high-stakes adventures to come. </description>
<setting>London, England, 1991 (United Kingdom)
Hogwarts School of Witchcraft and Wizardry, 1991 (United Kingdom)</setting>
<pages>309</pages>
<published>June 26th 1997</published>
<publisher>Scholastic In</publisher>
<avg_rating>4.47</avg_rating>
</book>

<book>
<title>Animal Farm</title>
<author>George Orwell</author>
<description>A farm is taken over by its overworked, mistreated animals. With flaming idealism and stirring slogans, they set out to create a paradise of progress, justice, and equality. Thus the stage is set for one of the most telling satiric fables ever penned –a razor-edged fairy tale for grown-ups that records the evolution from revolution against tyranny to a totalitarianism just as terrible.
When Animal Farm was first published, Stalinist Russia was seen as its target. Today it is devastatingly clear that wherever and whenever freedom is attacked, under whatever banner, the cutting clarity and savage comedy of George Orwell’s masterpiece have a meaning and message still ferociously fresh.</description>
<setting>England</setting>
<pages>141</pages>
<published>August 17th 1945</published>
<publisher>Signet Classics</publisher>
<avg_rating>3.95</avg_rating>
</book>

<book>
<title>The Catcher in the Rye</title>
<author>J.D. Salinger</author>
<description>The hero-narrator of The Catcher in the Rye is an ancient child of sixteen, a native New Yorker named Holden Caulfield. Through circumstances that tend to preclude adult, secondhand description, he leaves his prep school in Pennsylvania and goes underground in New York City for three days. The boy himself is at once too simple and too complex for us to make any final comment about him or his story. Perhaps the safest thing we can say about Holden is that he was born in the world not just strongly attracted to beauty but, almost, hopelessly impaled on it. There are many voices in this novel: children's voices, adult voices, underground voices-but Holden's voice is the most eloquent of all. Transcending his own vernacular, yet remaining marvelously faithful to it, he issues a perfectly articulated cry of mixed pain and pleasure. However, like most lovers and clowns and poets of the higher orders, he keeps most of the pain to, and for, himself. The pleasure he gives away, or sets aside, with all his heart. It is there for the reader who can handle it to keep.

J.D. Salinger's classic novel of teenage angst and rebellion was first published in 1951. The novel was included on Time's 2005 list of the 100 best English-language novels written since 1923. It was named by Modern Library and its readers as one of the 100 best English-language novels of the 20th century. It has been frequently challenged in the court for its liberal use of profanity and portrayal of sexuality and in the 1950's and 60's it was the novel that every teenage boy wants to read. </description>
<setting>New York City, New York, 1949 (United States)
Agerstown, Pennsylvania, 1949 (United States)</setting>
<pages>277</pages>
<published>July 16th 1951</published>
<publisher>Back Bay Books</publisher>
<avg_rating>3.81</avg_rating>
</book>


</fiction>
